services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: servicedesk-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "14333:1433"
    volumes:
      - servicedesk_sql_data:/var/opt/mssql
volumes:
  servicedesk_sql_data:
